name: instagram_application
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  assets:
    - assets/images/
 







  fonts:
    - family: GB
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700
    - family: GEB
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
          weight: 800
    - family: GH
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
          weight: 900
    # - family: GB
    #   fonts:
    #     - asset: assets/fonts/GilroyLight.ttf
    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500
    - family: GR
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400
        # - asset: assets/fonts/GilroyThin.ttf
    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500


